 const contacts: { id: number, firstName: string, lastName : string, phone : number, email : string, capitalInvested : number, address :string, state : string, zipcode: number}[] = [
    {
      id: 1,
      firstName: 'Will', 
      lastName: 'Ramirez', 
      phone: 6194559459, 
      email: 'willramirez630@gmail.com',
      capitalInvested: 100,
      address:'571 Dye Street',
      state: 'AZ',
      zipcode: 85012,

     },
     {
      id: 2,
      firstName: 'Michael', 
      lastName: 'Jordan', 
      phone: 61223232323, 
      email: 'mj@gmail.com',
      capitalInvested: 100,
      address: '572 Dye Street',
      state: 'AZ',
      zipcode: 85012,
    },
    {
      id: 3,
      firstName: 'Dan', 
      lastName: 'Ambramov', 
      phone: 6193231323, 
      email: 'danny@gfacebook.com',
      capitalInvested: 100,
      address: '573 Dye Street',
      state: 'AZ',
      zipcode: 85012,
   },
   {
   id: 4,
   firstName: 'Vitalik', 
   lastName: 'Buterin', 
   phone: 7181124444, 
   email: 'vb@etheruem.org',
   capitalInvested: 100,
   address: '574 Dye Street',
   state: 'AZ',
   zipcode: 85012,
  },
  {
  id: 5,
  firstName: 'Dave', 
  lastName: 'Goggins', 
  phone: 8183231234, 
  email: 'DG@gmail.com',
  capitalInvested: 100,
  address: '575 Dye Street',
  state: 'AZ',
  zipcode: 85012, 
  },
  {
  id: 6,
  firstName: 'Peter', 
  lastName: 'Pan', 
  phone: 2124559114, 
  email: 'ppan@gmail.com',
  capitalInvested: 100,
  address: '576 Dye Street',
  state: 'AZ',
  zipcode: 85012, 
  },
  {
  id: 7,
  firstName: 'Phill', 
  lastName: 'Jackson', 
  phone: 6177313223, 
  email: 'lakers@gmail.com',
  capitalInvested: 100,
  address: '577 Dye Street',
  state: 'AZ',
  zipcode: 85012, 
  },
  {
  id: 8,
  firstName: 'Derek', 
  lastName: 'Watts', 
  phone: 5182471123, 
  email: 'DaWatts@gmail.com',
  capitalInvested: 100,
  address: '578 Dye Street',
  state: 'AZ',
  zipcode: 85012, 
  },
  {
  id: 9,
  firstName: 'Peter', 
  lastName: 'Thiel', 
  phone: 7238115331, 
  email: 'petert@gmail.com',
  capitalInvested: 100,
  address: '579 Dye Street',
  state: 'AZ',
  zipcode: 85012, 
  },
  {
  id: 10,
  firstName: 'Elon', 
  lastName: 'Tusk', 
  phone: 2121315331, 
  email: 'et@gmail.com',
  capitalInvested: 100,
  address: '560 Dye Street',
   state: 'AZ',
   zipcode: 85012, 
  }
    ]
  export default contacts
 
  